# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 15

[[main]]
  name = "task"
  pageRef = "tasks"
  weight = 16

[[main]]
  name = "All"
  pageRef="all"
  weight = 20

[[main]]
  name = "Series"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Friend"
  pageRef = "friend"
  weight = 40
[[main]]
  name = "Doc"
  pageRef = "help"
  weight = 40

 [[footer]]
   name = "Series"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "About"
   pageRef = "info"
   weight = 20
