languageCode = "zh-CN"
languageName = "中文"
weight = 1
title = "春江花朝秋月夜"

[params]
    displayName = "中文"
    isoCode = "zh-CN"
    rtl = false
    dateFormat = "2 January 2006"
    logo = "img/author.png"
#    secondaryLogo = "PATH"
    description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#     copyright = "Copy, _right?_ :thinking_face:"

[author]
    name = "春江花朝秋月夜"
    image = "img/三叶.png"
    headline = "我一直在寻找着什么，寻找着某个人。"
    bio = "重湖叠𪩘清嘉。有三秋桂子，十里荷花。羌管弄晴，菱歌泛夜，嬉嬉钓叟莲娃。千骑拥高牙。乘醉听箫鼓，吟赏烟霞。异日图将好景，归去凤池夸。"
    links = [
        { bilibili = "https://space.bilibili.com/159283119?spm_id_from=333.1007.0.0" },
        { github = "https://github.com/ToDreamr" },
        { email = "mailto:aruixrain@gmail.com" },
        { wangyi = "https://music.163.com/#/user/home?id=568083850"},
        { gitee = "https://gitee.com/rainyheights"},
        { zhihu = "https://www.zhihu.com/people/san-qiu-luo-yue"},
    ]

#1.参与公司自研CMS系统的接口编写，保证系统与上下游系统的数据交互的稳定性，利用细粒度Transactional防止大事务死锁发生。
#2.参与维护Hub系统作为网关层面，交互ERP外围系统之间服务调用的语义转换，维护系统服务之间调用的稳定性。
#3.参与公司ERP外围系统，如PLM生命周期管理系统，使用SQL分析物料数据并进行导入，处理过复杂SQL的优化。

